migration to halo2.0
ruibaby/casper-halo pull request #17
Opened 2023-09-20 08:06 UTC by GodlessLiu

migration to halo 2.0

2023-09-21 05:51 UTC, wan92hen requested changes
顶部菜单的字体看起来太小了，跟其他内容的字体大小差距有点大；
文章模板引用顶部菜单代码有问题。

2023-09-21 05:51 UTC, wan92hen commented on templates/post.html
> +    <th:block th:replace="~{partials/floating-header : header(${post})}">
<th:block th:replace="~{partials/floating-header :: header(${post})}">

2023-09-21 06:32 UTC, GodlessLiu commented
> 顶部菜单的字体看起来太小了，跟其他内容的字体大小差距有点大； 文章模板引用顶部菜单代码有问题。

done

2023-09-22 06:35 UTC, wan92hen requested changes

2023-09-22 06:35 UTC, wan92hen commented on setting.yaml
> +          label: 归档页面背景图
```suggestion
        - $formkit: attachment
          name: cover
          label: 首页背景图
          value: ""
        - $formkit: attachment
          name: links_cover
          label: 友情链接页面背景图
        - $formkit: attachment
          name: archives_cover
          label: 归档页面背景图
```
图片选择建议使用 attachment 组件。

2023-12-01 19:12 UTC, leic4u commented
这个 PR 有进展么

2024-02-29 09:39 UTC, merged