根据最新的 Ghost Casper 主题重写支持 Halo v2 版本
ruibaby/casper-halo pull request #18
Opened 2023-12-29 08:41 UTC by wan92hen

2024-01-12 08:29 UTC, ruibaby reviewed
感谢参与贡献，以下是一些问题和建议。

2024-01-12 08:29 UTC, ruibaby commented on templates/author.html
> +							</footer> -->
没有用的话，可以删掉。

2024-01-12 08:29 UTC, ruibaby requested changes

2024-01-12 08:29 UTC, ruibaby commented on theme.yaml
> +  displayName: Casper
spec 中的 author 是必填，否则无法安装。

<img width="398" alt="图片" src="https://github.com/halo-dev/halo-theme-casper/assets/21301288/61bec842-a2cb-4bff-9ad7-e2840ebb2eeb">

2024-01-15 10:10 UTC, wan92hen commented
> 感谢参与贡献，以下是一些问题和建议。

Updated.

2024-02-29 09:39 UTC, merged